version: "3.8"
services:
  messagebroker_dev:
    image: "rabbitmq:3-management"
    ports:
      # Web interface
      - "7100:15672"
      - "7101:5672"
    volumes:
      - rabbitmq:/rabbitmq

volumes:
  rabbitmq:
    driver: local