version: "3.8"
services:
  broker:
    image: "rabbitmq:3-management"
    ports:
      - "7100:15672"
      - "7101:5672"
    volumes:
      - rabbitmq:/rabbitmq
  gateway:
    image: "viem:gateway"
    build: "ApiGateWay/"
    ports:
      - "5020:80"
      - "5021:443"
    environment: 
      - ASPNETCORE_ENVIRONMENT=ci
      - ASPNETCORE_URLS=https://+;http://+;

volumes:
  rabbitmq:
    driver: local